_wandb:
    value:
        cli_version: 0.21.0
        e:
            u5k1e0n6s80hocauba3wb8altty84y4m:
                codePath: sft4chat_trainer.py
                codePathLocal: sft4chat_trainer.py
                cpu_count: 40
                cpu_count_logical: 80
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1967317549056"
                        used: "1274187304960"
                email: 2300742382@qq.com
                executable: /home/kemove/.conda/envs/llm/bin/python
                gpu: NVIDIA GeForce RTX 4090 D
                gpu_count: 3
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 14592
                      memoryTotal: "51527024640"
                      name: NVIDIA GeForce RTX 4090 D
                      uuid: GPU-094ffb3e-e03b-7fa7-7d9b-4789ae115165
                    - architecture: Ada
                      cudaCores: 14592
                      memoryTotal: "51527024640"
                      name: NVIDIA GeForce RTX 4090 D
                      uuid: GPU-6be1403b-e613-a09e-2b9a-a90512452f2b
                    - architecture: Ada
                      cudaCores: 14592
                      memoryTotal: "51527024640"
                      name: NVIDIA GeForce RTX 4090 D
                      uuid: GPU-3a037af5-aca9-0738-0bf0-c279f6b5910d
                host: kemove-desktop
                memory:
                    total: "201325084672"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: /home/kemove/Courses/STF_LLM/Assignment_5/trainer/sft4chat_trainer.py
                python: CPython 3.12.9
                root: /home/kemove/Courses/STF_LLM/Assignment_5/trainer
                startedAt: "2026-02-03T11:44:15.018949Z"
                writerId: u5k1e0n6s80hocauba3wb8altty84y4m
        m:
            - "1": train_step
              "6":
                - 3
              "7": []
            - "1": valid_step
              "6":
                - 3
              "7": []
            - "2": train/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": valid/*
              "5": 2
              "6":
                - 1
              "7": []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 105
            "3":
                - 7
                - 13
                - 16
            "4": 3.12.9
            "5": 0.21.0
            "6": 4.57.6
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 32
clip_grad_norm:
    value: 1
device:
    value: cuda:0
epochs:
    value: 1
gradient_accumulation_steps:
    value: 8
lr:
    value: 5e-06
micro_batch_size:
    value: 4
model_id:
    value: Qwen/Qwen3-4B-Instruct-2507
seed:
    value: 42
seq_length:
    value: 1024
shuffle:
    value: false
train_path:
    value: ../data/ultrachat/train.jsonl
valid_path:
    value: ../data/ultrachat/valid.jsonl
wandb_project:
    value: SFT-Chat
